# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-06 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0002_auto_20200706_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='member',
            field=models.IntegerField(default=0, verbose_name='会员'),
        ),
        migrations.AlterField(
            model_name='user',
            name='super_u',
            field=models.IntegerField(default=0, verbose_name='管理员'),
        ),
    ]
