# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-09 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0004_auto_20200708_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='file_old',
            name='background',
            field=models.CharField(default=None, max_length=256, verbose_name='项目背景'),
        ),
        migrations.AddField(
            model_name='file_old',
            name='outline',
            field=models.CharField(default=None, max_length=256, verbose_name='项目概要'),
        ),
        migrations.AddField(
            model_name='file_old',
            name='path',
            field=models.CharField(default=None, max_length=256, verbose_name='保存文件的路径'),
        ),
        migrations.AddField(
            model_name='file_old',
            name='project_name',
            field=models.CharField(default=None, max_length=256, verbose_name='项目名称'),
        ),
    ]
