# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-09 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0005_auto_20200709_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Browsing_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_info', models.CharField(default=None, max_length=256, verbose_name='具体浏览过程')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.CharField(max_length=11, unique=True, verbose_name='顺序编号')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_process', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '浏览记录',
                'db_table': 'tb_process',
            },
        ),
    ]
