# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-09 03:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0006_browsing_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsing_process',
            name='file_old',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='project', to='index_qt.File_old', verbose_name='项目id'),
        ),
    ]
