# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-10 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0007_browsing_process_file_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_tou',
            field=models.CharField(default=None, max_length=256, verbose_name='头像'),
        ),
    ]
