# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-11 09:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0009_auto_20200711_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browsing_process',
            name='file_old',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='index_qt.File_old', verbose_name='项目id'),
        ),
        migrations.AlterField(
            model_name='browsing_process',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_process', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
        migrations.AlterField(
            model_name='file_old',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
