# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-07-13 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0010_auto_20200711_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='browsing_process',
            name='is_delete',
            field=models.CharField(default=0, max_length=11, verbose_name='是否显示'),
        ),
    ]
