# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-12-28 06:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0014_auto_20201228_0146'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Member',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('is_delete', models.CharField(default=0, max_length=11, verbose_name='是否删除')),
        #     ],
        #     options={
        #         'verbose_name': '会员表',
        #         'db_table': 'tb_member',
        #     },
        # ),
        # migrations.CreateModel(
        #     name='MemberType',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('member_name', models.CharField(default=None, max_length=65535, verbose_name='会员名称')),
        #         ('number', models.IntegerField(verbose_name='分析条数')),
        #         ('projects', models.IntegerField(default=0, verbose_name='项目数量')),
        #     ],
        #     options={
        #         'verbose_name': '会员类型表',
        #         'db_table': 'tb_type',
        #     },
        # ),
        # migrations.AddField(
        #     model_name='browsing_process',
        #     name='is_latest',
        #     field=models.IntegerField(default=0, verbose_name='是否是最新的数据'),
        # ),
        # migrations.AddField(
        #     model_name='file_old',
        #     name='last_time',
        #     field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        # ),
        # migrations.AddField(
        #     model_name='file_old',
        #     name='path_pa',
        #     field=models.CharField(default=None, max_length=65535, verbose_name='保存文件的路径'),
        # ),
        migrations.AddField(
            model_name='modelbase',
            name='versions',
            field=models.CharField(default=None, max_length=65535, verbose_name='版本数'),
        ),
        # migrations.AlterField(
        #     model_name='browsing_process',
        #     name='order',
        #     field=models.IntegerField(verbose_name='顺序编号'),
        # ),
        # migrations.AddField(
        #     model_name='member',
        #     name='member_type',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tb_type', to='index_qt.MemberType', verbose_name='会员级别'),
        # ),
        # migrations.AddField(
        #     model_name='member',
        #     name='user',
        #     field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        # ),
    ]
