# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-11 03:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0015_auto_20201228_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(default=None, max_length=65535, verbose_name='视频教程标题')),
                ('video_background', models.CharField(default=None, max_length=65535, verbose_name='视频教程说明')),
                ('video_info', models.CharField(default=None, max_length=65535, verbose_name='视频图片')),
                ('video_link', models.CharField(default=None, max_length=65535, verbose_name='视频链接')),
            ],
            options={
                'verbose_name': '视频教程',
                'db_table': 'tb_help_video',
            },
        ),

    ]
