# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-12 06:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0017_auto_20210111_0829'),
    ]

    operations = [
  
        migrations.CreateModel(
            name='Post_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_content', models.CharField(max_length=65535, verbose_name='发布内容')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('post_image', models.CharField(max_length=65535, verbose_name='发布图片')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_library', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '发帖',
                'db_table': 'tb_post',
            },
        ),
    ]
