# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-01-12 06:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0018_auto_20210112_0616'),
    ]

    operations = [

        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='评分分数')),
                ('modelbase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_library', to='index_qt.Modelbase', verbose_name='模型库')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_library', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '评分',
                'db_table': 'tb_score',
            },
        ),

    ]
