# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-04 11:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0021_auto_20210128_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10, verbose_name='单价'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_payment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='index_qt.OrderInfo', verbose_name='订单表信息'),
        ),

    ]
