# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-08 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0022_auto_20210204_1124'),
    ]

    operations = [

        # migrations.AlterField(
        #     model_name='payment',
        #     name='order_payment',
        #     field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='index_qt.OrderInfo', verbose_name='订单表信息'),
        # ),

    ]
