# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-09 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0023_auto_20210208_0807'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='member',
        #     name='member_initial_time',
        #     field=models.DateTimeField(default=None, verbose_name='会员初始时间'),
        # ),
        # migrations.AddField(
        #     model_name='member',
        #     name='member_last_time',
        #     field=models.DateTimeField(default=None, verbose_name='会员到期时间'),
        # ),
    ]
