# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-02-09 18:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index_qt', '0024_auto_20210209_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_time', models.DateTimeField(auto_now_add=True, verbose_name='当天时间')),
                ('login_total', models.IntegerField(verbose_name="登录用户量",default=0)),
                ('total_total', models.IntegerField(verbose_name="当天注册量",default=0)),
            ],
            options={
                'verbose_name': '每天用户数据量',
                'db_table': 'tb_user_analysis',
            },
        ),

    ]
